POST http://localhost:3001/api/templates
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjYxNzNlYmFjNmI4OGFiMTczMzIzOTQ2NSIsImlhdCI6MTYzNTE0MzU1Nn0.EyoI2FvzNG2UvQ57rA9jggVdHE2vl1-w_yHV23NARsI

{
    "template": true,
    "sets": [
        {
            "weight": 60,
            "repetitions": 8,
            "exercise": "6172a5430c53ebb7e0da9873"
        },
        {
            "weight": 60,
            "repetitions": 8,
            "exercise": "6172a5430c53ebb7e0da9873"
        },
        {
            "weight": 60,
            "repetitions": 8,
            "exercise": "6172a5430c53ebb7e0da9873"
        }
    ]
}