POST http://localhost:3001/api/templates
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxMiIsImlkIjoiNjE3OTNlMzQyNDczNWJiNzZjN2JkYTZhIiwiaWF0IjoxNjM1MzM1ODYwfQ.FTJQAI8fOnCVt06-OMcLX0WWkQ_iJyZey3tSlaBue_Q

{
    "template": true,
    "sets": [
        {
            "weight": 60,
            "repetitions": 8,
            "exercise": "6172a5430c53ebb7e0da9873"
        },
        {
            "weight": 60,
            "repetitions": 8,
            "exercise": "6172a5430c53ebb7e0da9873"
        },
        {
            "weight": 60,
            "repetitions": 8,
            "exercise": "6172a5430c53ebb7e0da9873"
        }
    ]
}