DELETE http://localhost:3001/api/templates/6183826190d09ecf90396bd3
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxMjMiLCJpZCI6IjYxN2VkMjllY2Y2ZjU0MjdhZGNlNzZhMiIsImlhdCI6MTYzNTkyNTgzOH0.urYtiLNFdoucnWgXlDclh0lgk8d_pDHKldGRSxZ_2vA
