GET http://localhost:3001/api/workouts
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvcmlzMiIsImlkIjoiNjE3MjZkNzkzOGU3Mjg2MzFmMWNjNmIwIiwiaWF0IjoxNjM0ODg5MTAwfQ.PkVsTNFjOgEF8boKMQfn5VSHc564gxgHcXPmX1Mv25Q
