name: Deployment pipeline

on:
  push:
    branches:
      - CI-CD
      - main
  pull_request:
    branches: [main]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: npm install
        run: npm --prefix ./client/ install
      - name: npm build
        run: npm --prefix ./client/ run build
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "www-design-gym"
          heroku_email: "touko.lonka@aalto.fi"
          healthcheck: "https://www-design-gym.herokuapp.com/api/health"
          rollbackonhealthcheckfailed: true